import React from "react";
import { FileText, Download, Printer } from "lucide-react";
import { DocItem } from "./DocList";
import { DocStatusBadge } from "./DocStatusBadge";
import { useI18n } from "../../../app/providers/I18nProvider";
import { Button } from "../../../shared/ui/button";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "../../../shared/ui/alert-dialog";

// ---------------------------------------------------------------------------
// Helpers — PDF/print + .txt download
// ---------------------------------------------------------------------------

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function openPrintablePdf(doc: DocItem) {
  const win = window.open("", "_blank", "width=820,height=1000");
  if (!win) return;
  const owner = doc.owner ? `${doc.owner}` : "—";
  const statusLabel = doc.status ?? "—";
  const updated = doc.updatedAt ?? new Date().toISOString().slice(0, 10);

  win.document.write(`<!DOCTYPE html>
<html lang="uz">
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(doc.title)}</title>
    <style>
      @page { margin: 24mm 20mm; }
      * { box-sizing: border-box; }
      body {
        font-family: 'Helvetica Neue', Arial, 'Noto Sans', sans-serif;
        color: #0f172a;
        margin: 0;
        padding: 32px 40px;
        line-height: 1.6;
      }
      .brand {
        font-size: 11px;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        color: #4f46e5;
        font-weight: 600;
      }
      h1 {
        font-size: 24px;
        margin: 8px 0 16px;
        color: #0f172a;
      }
      .meta {
        display: flex;
        flex-wrap: wrap;
        gap: 16px;
        font-size: 12px;
        color: #475569;
        padding: 12px 0;
        border-top: 1px solid #e2e8f0;
        border-bottom: 1px solid #e2e8f0;
        margin-bottom: 24px;
      }
      .meta b { color: #0f172a; font-weight: 600; }
      .content {
        white-space: pre-wrap;
        font-size: 14px;
        color: #1e293b;
      }
      .footer {
        margin-top: 48px;
        padding-top: 16px;
        border-top: 1px solid #e2e8f0;
        font-size: 10px;
        color: #94a3b8;
        text-align: center;
      }
      @media print {
        body { padding: 0; }
        .no-print { display: none; }
      }
    </style>
  </head>
  <body>
    <div class="brand">AI Business Concierge — Hujjat</div>
    <h1>${escapeHtml(doc.title)}</h1>
    <div class="meta">
      <span><b>Mas'ul:</b> ${escapeHtml(owner)}</span>
      <span><b>Status:</b> ${escapeHtml(statusLabel)}</span>
      <span><b>Yangilandi:</b> ${escapeHtml(updated)}</span>
    </div>
    <div class="content">${escapeHtml(doc.content ?? "")}</div>
    <div class="footer">
      Generated by AI Business Concierge · ${new Date().toLocaleString()}
    </div>
  </body>
</html>`);
  win.document.close();
  win.setTimeout(() => {
    win.focus();
    win.print();
  }, 300);
}

function downloadAsTxt(doc: DocItem) {
  const lines = [
    doc.title,
    "=".repeat(Math.min(doc.title.length, 60)),
    "",
    `Mas'ul: ${doc.owner ?? "—"}`,
    `Status: ${doc.status ?? "—"}`,
    `Yangilandi: ${doc.updatedAt ?? new Date().toISOString().slice(0, 10)}`,
    "",
    "---",
    "",
    doc.content ?? "",
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = window.document.createElement("a");
  a.href = url;
  a.download = `${doc.title.replace(/[^\wÀ-￿.-]+/g, "_")}.txt`;
  window.document.body.appendChild(a);
  a.click();
  window.document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function DocDetail({
  doc,
  onEdit,
  onDelete,
}: {
  doc?: DocItem;
  onEdit?: () => void;
  onDelete?: () => Promise<void>;
}) {
  const { translate } = useI18n();
  const [deleting, setDeleting] = React.useState(false);
  const [deleteError, setDeleteError] = React.useState<string | null>(null);

  async function handleDelete() {
    if (!onDelete) return;
    setDeleting(true);
    setDeleteError(null);
    try {
      await onDelete();
    } catch (err) {
      setDeleteError(err instanceof Error ? err.message : translate("docs.deleteError"));
    } finally {
      setDeleting(false);
    }
  }

  if (!doc) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-400">
        <FileText size={32} className="mb-2 opacity-40" />
        <p className="text-sm">{translate("docs.select")}</p>
      </div>
    );
  }

  return (
    <div className="p-6">
      <div className="flex items-start justify-between mb-4 gap-3 flex-wrap">
        <div>
          <h2 className="text-xl font-bold text-slate-900">{doc.title}</h2>
          <p className="text-xs text-slate-500 mt-1">
            {translate("docs.owner")}: {doc.owner ?? "—"}
          </p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <DocStatusBadge status={doc.status} />

          <Button
            variant="outline"
            size="sm"
            onClick={() => openPrintablePdf(doc)}
            title={translate("docs.viewPdfHint")}
          >
            <Printer size={14} className="mr-1.5" />
            {translate("docs.viewPdf")}
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={() => downloadAsTxt(doc)}
            title={translate("docs.downloadHint")}
          >
            <Download size={14} className="mr-1.5" />
            {translate("docs.download")}
          </Button>

          {onEdit && (
            <Button variant="outline" onClick={onEdit}>
              {translate("docs.editAction")}
            </Button>
          )}
          {onDelete && (
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button variant="destructive" disabled={deleting}>
                  {translate("docs.deleteAction")}
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>{translate("docs.deleteTitle")}</AlertDialogTitle>
                  <AlertDialogDescription>
                    {translate("docs.deleteDescription")}
                  </AlertDialogDescription>
                </AlertDialogHeader>
                {deleteError && <p className="text-sm text-rose-600">{deleteError}</p>}
                <AlertDialogFooter>
                  <AlertDialogCancel disabled={deleting}>
                    {translate("common.cancel")}
                  </AlertDialogCancel>
                  <AlertDialogAction onClick={handleDelete} disabled={deleting}>
                    {deleting ? "..." : translate("docs.deleteConfirm")}
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          )}
        </div>
      </div>

      <div className="text-sm text-slate-600 leading-relaxed">
        <p className="mb-3 whitespace-pre-line">
          {doc.content ||
            "Ushbu hujjat kompaniya ichki siyosatlari va jarayonlariga tegishli. Mazmuni tekshirilmoqda va tasdiqlangandan so'ng tegishli bo'limlarga tarqatiladi."}
        </p>
        <p className="text-xs text-slate-400">
          {translate("docs.updatedAt")}: {doc.updatedAt}
        </p>
      </div>
    </div>
  );
}
